//token验证白名单
module.exports = [
    '/createType',
    '/findTypeList',
    '/toggleTypeStatus',
    '/typeDataByTypeId',
    '/editType',
    '/removeType',
    '/typeCount',
    '/userInfo',
    '/postProduct',
    '/typeData',
    '/productList',
    '/productCount',
    '/productStatus',
    '/removeProduct',
    '/productByProId',
    '/editProduct',
]